// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoELJMgBlik2nSf_hfj-nMn_eJvYisQs',
    appId: '1:914055317756:android:23881d5da87b588ac26f79',
    messagingSenderId: '914055317756',
    projectId: 'evently-c19-6de8d',
    storageBucket: 'evently-c19-6de8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1QrABWX12PNBv1IuZHjKPxaoEf7Rdb4',
    appId: '1:914055317756:ios:0401a3839e115720c26f79',
    messagingSenderId: '914055317756',
    projectId: 'evently-c19-6de8d',
    storageBucket: 'evently-c19-6de8d.firebasestorage.app',
    androidClientId: '914055317756-4703ememqv482i0t348pifie7up1i3un.apps.googleusercontent.com',
    iosClientId: '914055317756-ier5fmrg1j006fev7dvjqhdfutvm07fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC19',
  );
}
